export const FETCH_GENERIC_NATIONALITIES = "generic/FETCH_NATIONALITIES";
export const SET_GENERIC_NATIONALITIES = "generic/SET_NATIONALITIES";
export const FETCH_GENERIC_SEXES = "generic/FETCH_SEXES";
export const SET_GENERIC_SEXES = "generic/SET_SEXES";
export const FETCH_GENERIC_DESTINATIONS = "generic/FETCH_DESTINATIONS";
export const FETCH_GENERIC_TRAVEL_EVENTS = "generic/FETCH_TRAVEL_EVENTS";
export const SET_GENERIC_DESTINATIONS = "generic/SET_DESTINATIONS";
export const SET_GENERIC_TRAVEL_EVENTS = "generic/SET_TRAVEL_EVENTS";
export const SET_GENERIC_GLOBAL_SNACKBAR_CONFIGS =
  "generic/SET_GLOBAL_SNACKBAR_CONFIGS";
export const FETCH_GENERIC_TRANSPORTATION = "FETCH_GENERIC_TRANSPORTATION";
export const SET_GENERIC_TRANSPORTATION = "SET_GENERIC_TRANSPORTATION";
