export const CREATE_TRAVEL_STORY_POST = "post/CREATE_TRAVEL_STORY";
export const CREATE_ITINERARY_POST = "post/CREATE_ITINERARY";
export const FETCH_POSTS = "post/FETCH";
export const FETCH_POST_COMMENTS = "post/FETCH_COMMENTS";
export const FETCH_POST_COMMENT_REPLIES = "post/FETCH_COMMENT_REPLIES";
export const GET_POST_SOFT_DETAILS = "post/GET_SOFT_DETAILS";
export const SEND_POST_COMMENT = "post/SEND_COMMENT";
export const SEND_POST_COMMENT_REPLY = "post/SEND_COMMENT_REPLY";
export const SEND_POST_REACTION = "post/SEND_REACTION";
export const REMOVE_POST_REACTION = "post/REMOVE_REACTION";
export const SEND_POST_COMMENT_REACTION = "post/SEND_COMMENT_REACTION";
export const REMOVE_POST_COMMENT_REACTION = "post/REMOVE_COMMENT_REACTION";
export const SEND_POST_COMMENT_REPLY_REACTION =
  "post/SEND_COMMENT_REPLY_REACTION";
export const REMOVE_POST_COMMENT_REPLY_REACTION =
  "post/REMOVE_COMMENT_REPLY_REACTION";
export const SAVE_TRAVEL_STORY_POST_DRAFT = "post/SAVE_TRAVEL_STORY_DRAFT";
export const FETCH_TRAVEL_STORY_POST_DRAFTS_PREVIEW =
  "post/FETCH_TRAVEL_STORY_DRAFTS_PREVIEW";
export const GET_TRAVEL_STORY_POST_DETAILS = "post/GET_TRAVEL_STORY_DETAILS";
export const UPDATE_TRAVEL_STORY_POST_DRAFT = "post/UPDATE_TRAVEL_STORY_DRAFT";
export const UPDATE_ITINERARY_POST_DRAFT = "post/UPDATE_ITINERARY_DRAFT";
export const FETCH_ITINERARY_POST_DRAFTS_PREVIEW =
  "post/FETCH_ITINERARY_DRAFTS_PREVIEW";
export const SAVE_ITINERARY_POST_DRAFT = "post/SAVE_ITINERARY_DRAFT";
export const GET_ITINERARY_POST_DETAILS = "post/GET_ITINERARY_DETAILS";
export const GET_POST_TOP_CATEGORIES = "post/GET_TOP_CATEGORIES";
export const SET_POST_TOP_CATEGORIES = "post/SET_TOP_CATEGORIES";
