export const CREATE_TRAVEL_STORY_POST = "post/CREATE_TRAVEL_STORY";
export const CREATE_ITINERARY_POST = "post/CREATE_ITINERARY";
export const FETCH_POSTS = "post/FETCH";
export const FETCH_POST_COMMENTS = "post/FETCH_COMMENTS";
export const FETCH_POST_COMMENT_REPLIES = "post/FETCH_COMMENT_REPLIES";
export const GET_POST_SOFT_DETAILS = "post/GET_SOFT_DETAILS";
export const SEND_POST_COMMENT = "post/SEND_COMMENT";
export const SEND_POST_COMMENT_REPLY = "post/SEND_COMMENT_REPLY";
export const SEND_POST_REACTION = "post/SEND_REACTION";
export const REMOVE_POST_REACTION = "post/REMOVE_REACTION";
export const SEND_POST_COMMENT_REACTION = "post/SEND_COMMENT_REACTION";
export const REMOVE_POST_COMMENT_REACTION = "post/REMOVE_COMMENT_REACTION";
export const SEND_POST_COMMENT_REPLY_REACTION =
  "post/SEND_COMMENT_REPLY_REACTION";
export const REMOVE_POST_COMMENT_REPLY_REACTION =
  "post/REMOVE_COMMENT_REPLY_REACTION";
export const SAVE_TRAVEL_STORY_POST_DRAFT = "post/SAVE_TRAVEL_STORY_DRAFT";
